[package]
name = "xsync-protocol-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[workspace]

[dependencies]
libfuzzer-sys = "0.4"
xsync-core = { path = "../crates/xsync-core" }

[[bin]]
name = "protocol"
path = "fuzz_targets/protocol.rs"
test = false
doc = false
