#!/usr/bin/env python3
"""Generate the checked-in xsync/f2 compatibility matrix from v2 vectors."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VECTORS = ROOT / "protocol-v2-vectors" / "payload-v1.tsv"
OUTPUT = ROOT / "docs" / "compatibility-matrix.md"


def vector_digest() -> str:
    data = VECTORS.read_bytes()
    return hashlib.sha256(data).hexdigest()


def vector_counts() -> tuple[int, int]:
    valid = malformed = 0
    for line in VECTORS.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        fields = line.split("\t")
        if len(fields) != 5:
            raise ValueError(f"invalid vector row: {line!r}")
        if fields[1] == "malformed":
            malformed += 1
        else:
            valid += 1
    return valid, malformed


def render() -> str:
    valid, malformed = vector_counts()
    digest = vector_digest()
    return f"""# xsync/f2 compatibility matrix

Generated by `scripts/generate-compatibility-matrix.py` from
`protocol-v2-vectors/payload-v1.tsv`.

- Vector SHA-256: `{digest}`
- Vectors consumed: {valid} valid, {malformed} malformed
- Matrix policy: a v1 peer never receives v2 frames; a v2-capable pair uses
  v2 only after both negotiation and browse capability bits are present.

| Client | Server | Result |
|---|---|---|
| xsync v1 | xsync v1 | works: v1 sync |
| xsync v2 | xsync v1 | works with reduced capability: v1 push/pull; browse unavailable |
| xsync v1 | xsync v2 | works with reduced capability: v1 sync; no v2 frames sent |
| xsync v2 | xsync v2 | works: v2 browse, mutation, fetch, and publish |
| f2 v2 | xsync v1 | works with reduced capability: v1-compatible transport; browse unavailable |
| f2 v2 | xsync v2 | works with reduced capability: f2's current client consumes browse types 14–21; mutation/fetch/publish remain unavailable until f2 implements types 22–35 |
| xsync v2 | f2 v2 | works with reduced capability: the shared browse subset is available; unsupported mutation/fetch/publish operations are not advertised |
| any client | missing/old xsync | refuses: `xs not found on remote host — install it or check PATH`, or the version-skew probe result |

The asymmetric deployment case is explicit: a long-lived old agent staged
months before a new client remains usable for v1 sync, while the client reports
browse as unavailable and offers an agent upgrade. It never probes by sending a
v2 data frame.

The generated digest changes whenever the canonical conformance corpus changes;
the owning protocol change must update this file and the f2 copied fixture in
the same release coordination window.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the checked-in file is stale")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"{OUTPUT} is stale; run {Path(__file__).name}")
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
