#!/usr/bin/env python3
"""Generate the checked-in xsync/f2 compatibility matrix from v2 vectors."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VECTORS = ROOT / "protocol-v2-vectors" / "payload-v1.tsv"
VECTORS_V3 = ROOT / "protocol-v3-vectors" / "payload-v1.tsv"
OUTPUT = ROOT / "docs" / "compatibility-matrix.md"


def vector_digest(path: Path = VECTORS) -> str:
    data = path.read_bytes()
    return hashlib.sha256(data).hexdigest()


def vector_counts(path: Path = VECTORS) -> tuple[int, int]:
    valid = malformed = 0
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        fields = line.split("\t")
        if len(fields) != 5:
            raise ValueError(f"invalid vector row: {line!r}")
        if fields[1] == "malformed":
            malformed += 1
        else:
            valid += 1
    return valid, malformed


def render() -> str:
    valid, malformed = vector_counts()
    digest = vector_digest()
    valid_v3, malformed_v3 = vector_counts(VECTORS_V3)
    digest_v3 = vector_digest(VECTORS_V3)
    return f"""# xsync/f2 compatibility matrix

Generated by `scripts/generate-compatibility-matrix.py` from
`protocol-v2-vectors/payload-v1.tsv` and `protocol-v3-vectors/payload-v1.tsv`.

- v2 vector SHA-256: `{digest}`
- v2 vectors consumed: {valid} valid, {malformed} malformed
- v3 vector SHA-256: `{digest_v3}`
- v3 vectors consumed: {valid_v3} valid, {malformed_v3} malformed
- Matrix policy: native sync v2 carries sender-provided segment digests. A v1
  peer is rejected by the native decoder; callers must use the rsync fallback
  or upgrade the peer. Browse v2 remains selected only after both negotiation
  and browse capability bits are present. Protocol v3 (filesystem surface) is
  selected only after both negotiation and `CAP_FS_V3` bits are present; its
  Phase 1 table is frozen and a session-role peer advertises the bit; the
  filesystem verbs themselves are not implemented yet.

| Client | Server | Result |
|---|---|---|
| xsync v1 | xsync v1 | works: v1 sync |
| xsync v2 | xsync v1 | works with reduced capability: v1 push/pull; browse unavailable |
| xsync v1 | xsync v2 | works with reduced capability: v1 sync; no v2 frames sent |
| xsync v2 | xsync v2 | works: v2 browse, mutation, fetch, and publish |
| f2 v2 | xsync v1 | works with reduced capability: v1-compatible transport; browse unavailable |
| f2 v2 | xsync v2 | works with reduced capability: f2's current client consumes browse types 14–21; mutation/fetch/publish remain unavailable until f2 implements types 22–35 |
| xsync v2 | f2 v2 | works with reduced capability: the shared browse subset is available; unsupported mutation/fetch/publish operations are not advertised |
| xsync v3 | xsync v1 | works with reduced capability: v1 sync; neither browse nor filesystem session |
| xsync v3 | xsync v2 | works with reduced capability: v2 browse, mutation, fetch, and publish; the older peer ignores `CAP_FS_V3`; random access unavailable |
| xsync v2 | xsync v3 | works with reduced capability: v2 selected; no v3 frame sent |
| xsync v3 | xsync v3 | works: v3 selected and features exchanged; filesystem verbs answer `EOPNOTSUPP` until the E1-S4/E4/E5 handlers land |
| f2 v2 | xsync v3 | works with reduced capability: as against xsync v2; f2 does not implement v3 |
| any client | missing/old xsync | refuses: `xs not found on remote host — install it or check PATH`, or the version-skew probe result |

The asymmetric deployment case is explicit: a long-lived old agent staged
months before a new client remains usable for v1 sync, while the client reports
browse as unavailable and offers an agent upgrade. It never probes by sending a
v2 data frame.

The generated digest changes whenever the canonical conformance corpus changes;
the owning protocol change must update this file and the f2 copied fixture in
the same release coordination window.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the checked-in file is stale")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"{OUTPUT} is stale; run {Path(__file__).name}")
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
