#!/usr/bin/env bash
# Build and package one release artifact. Story D2.2.
#
# Deliberately a script rather than inline CI steps: a release process that only
# exists inside a workflow cannot be run, inspected, or debugged without pushing
# a tag, which is exactly when you least want to be debugging it.
#
#   scripts/package-release.sh <target-triple> [output-dir]
set -euo pipefail

target=${1:?usage: package-release.sh <target-triple> [output-dir]}
outdir=${2:-dist}
root=$(cd "$(dirname "$0")/.." && pwd)
cd "$root"

version=$(sed -n 's/^version = "\(.*\)"$/\1/p' Cargo.toml | head -1)
if [ -z "$version" ]; then
    printf 'cannot read version from Cargo.toml\n' >&2
    exit 1
fi

# Pin the build date so two runs from the same commit agree. Without this the
# timestamp alone makes binaries differ, which defeats the reproducibility the
# story asks for. Prefer the commit's own time so the value is a property of the
# source rather than of when the build happened to run.
if [ -z "${SOURCE_DATE_EPOCH:-}" ]; then
    if SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct 2>/dev/null) && [ -n "$SOURCE_DATE_EPOCH" ]; then
        :
    else
        # No git history to take a date from, so "now" is the only option -- and
        # that makes this build unreproducible. Say so rather than let a caller
        # believe an artifact is reproducible when it silently is not.
        SOURCE_DATE_EPOCH=$(date -u +%s)
        printf 'warning: no git history here, so SOURCE_DATE_EPOCH falls back to the current time.\n' >&2
        printf '         This build is NOT reproducible. Set SOURCE_DATE_EPOCH explicitly to make it so.\n' >&2
    fi
    export SOURCE_DATE_EPOCH
fi

printf 'building %s (version %s, SOURCE_DATE_EPOCH=%s)\n' "$target" "$version" "$SOURCE_DATE_EPOCH"
# `cross` for targets this machine cannot build natively; plain cargo otherwise.
${XSYNC_CARGO:-cargo} build --release --locked --target "$target" -p xsync

case "$target" in
    *windows*) binary=xs.exe ;;
    *)         binary=xs ;;
esac
built="target/$target/release/$binary"
[ -f "$built" ] || { printf 'expected binary missing: %s\n' "$built" >&2; exit 1; }

stage="$outdir/xsync-$version-$target"
rm -rf "$stage"
mkdir -p "$stage"
cp "$built" "$stage/$binary"
cp LICENSE-MIT LICENSE-APACHE "$stage/"
cp README.md "$stage/README.md"

# Man page and completions are generated by the binary itself, from the same
# parser that defines the flags, so they cannot describe options that no longer
# exist. Skipped when cross-compiling, since the artifact will not run here.
if "$stage/$binary" --version >/dev/null 2>&1; then
    mkdir -p "$stage/man" "$stage/completions"
    "$stage/$binary" --man > "$stage/man/xs.1"
    for shell in bash zsh fish powershell; do
        case "$shell" in
            bash)       out="xs.bash" ;;
            zsh)        out="_xs" ;;
            fish)       out="xs.fish" ;;
            powershell) out="_xs.ps1" ;;
        esac
        "$stage/$binary" --completions "$shell" > "$stage/completions/$out"
    done
    printf 'included man page and completions\n'
else
    printf 'cross-compiled artifact: skipping man page and completions\n' >&2
fi

mkdir -p "$outdir"

# Normalise mtimes before archiving. GNU tar's --mtime/--sort/--owner are not
# accepted by the bsdtar macOS ships, and the first version of this script fell
# through to a plain `tar -czf` there, producing archives that differed between
# runs even though the binaries inside them were byte-identical. Setting the
# times on disk works with either tar.
stamp=$(TZ=UTC date -r "$SOURCE_DATE_EPOCH" +%Y%m%d%H%M.%S 2>/dev/null \
     || TZ=UTC date -u -d "@$SOURCE_DATE_EPOCH" +%Y%m%d%H%M.%S)
# `touch -t` interprets the stamp in the *local* timezone while the stamp above
# is computed in UTC, so without forcing TZ the recorded mtimes are off by the
# machine's UTC offset -- harmless for reproducibility on one host, but it
# writes wrong timestamps and makes tar warn about files "in the future".
find "$stage" -exec env TZ=UTC touch -t "$stamp" {} +

# GNU tar and the bsdtar macOS ships spell ownership flags differently
# (--owner/--group versus --uid/--gid) and each rejects the other's. Probe once
# rather than guess: guessing wrong here breaks the release on whichever half of
# the runners was not tested.
tar_owner_flags=""
if echo test | tar --owner=0 --group=0 --numeric-owner -cf /dev/null -T - 2>/dev/null; then
    tar_owner_flags="--owner=0 --group=0 --numeric-owner"
elif echo test | tar --uid 0 --gid 0 --numeric-owner -cf /dev/null -T - 2>/dev/null; then
    tar_owner_flags="--uid 0 --gid 0 --numeric-owner"
fi

case "$target" in
    *windows*)
        archive="$outdir/xsync-$version-$target.zip"
        rm -f "$archive"
        # -X drops extra attributes that vary per machine; the normalised
        # mtimes above supply the rest of the determinism.
        (cd "$outdir" && find "$(basename "$stage")" -type f | LC_ALL=C sort | zip -qX "$(basename "$archive")" -@)
        ;;
    *)
        archive="$outdir/xsync-$version-$target.tar.gz"
        rm -f "$archive"
        # Files only: naming the directory as well made tar recurse into it and
        # archive every member twice, doubling the artifact while still hashing
        # identically between runs. Reproducible and wrong is still wrong.
        # Explicit sorted member list rather than --sort, and `gzip -n` so the
        # compressor does not stamp its own timestamp into the header.
        (cd "$outdir" \
            && find "$(basename "$stage")" -type f -print0 | LC_ALL=C sort -z \
            | tar --null -T - $tar_owner_flags -cf -) \
            | gzip -n -9 > "$archive"
        ;;
esac

rm -rf "$stage"
printf 'packaged %s (%s bytes)\n' "$archive" "$(wc -c < "$archive" | tr -d ' ')"
