#!/usr/bin/env python3
"""BENCHMARKSv4 matrix: 3 corpora x 3 hosts x {rsync -az, xs --streams 4}.

Long-running (hours). Design notes:
  * Resumable -- every finished cell is appended to results.jsonl and skipped
    on a rerun, so the matrix can be interrupted and continued.
  * BENCHMARKSv4.md is regenerated after every cell, so partial results are
    always readable rather than arriving only at the end.
  * Fail-soft -- a failed or timed-out cell is recorded and the matrix goes on.

Fairness rules, same as every other measurement in this repo:
  * fresh destination per run; teardown never inside the timed window
  * remote `sync` inside the timed window, so neither tool is scored on data
    still sitting in the receiver's page cache
  * arms run back to back per (host, corpus) so they share link conditions
  * landed file count and exit status verified per run
"""
import json, os, pathlib, subprocess, sys, time

ROOT = pathlib.Path("/Users/sanjee/projects/xsync")
XS = ROOT / "target/release/xs"
OUT = ROOT / "benches/results/v4"
RESULTS = OUT / "results.jsonl"
DOC = ROOT / "BENCHMARKSv4.md"

REPS = int(os.environ.get("MATRIX_REPS", "2"))
CELL_TIMEOUT = int(os.environ.get("MATRIX_TIMEOUT", "7200"))  # seconds

HOSTS = [
    ("mars",  "sanjee@mars.local",  "switched gigabit"),
    ("freya", "sanjee@freya.local", "~800 Mbit mesh (router2)"),
    ("orion", "root@orion.local",   "switched gigabit, Pi 5"),
]
CORPORA = [
    ("manga",    ROOT / "corpora/Manga",    56,      3.75),
    ("congress", ROOT / "corpora/congress", 1318771, 10.23),
    ("cb7",      ROOT / "corpora/cb7",      204577,  58.25),
]
ARMS = ["rsync -az", "xs --streams 4"]


def sh(cmd, timeout=None):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=timeout)


def remote(host, cmd, timeout=1800):
    return sh(f"ssh -o ConnectTimeout=15 {host} {cmd!r}", timeout=timeout)


def load_done():
    done = {}
    if RESULTS.exists():
        for line in RESULTS.read_text().splitlines():
            if line.strip():
                r = json.loads(line)
                done[(r["host"], r["corpus"], r["arm"], r["rep"])] = r
    return done


def record(row):
    OUT.mkdir(parents=True, exist_ok=True)
    with RESULTS.open("a") as fh:
        fh.write(json.dumps(row) + "\n")


def run_cell(hname, host, cname, src, expect, gib, arm, rep):
    dst = f"~/bench4-{cname}"
    remote(host, f"rm -rf {dst}; mkdir -p {dst}")
    remote(host, "sync")
    time.sleep(3)

    if arm.startswith("rsync"):
        cmd = f"rsync -az {src}/ {host}:{dst}/"
    else:
        cmd = f"{XS} --streams 4 {src}/ {host}:{dst}/"

    t0 = time.monotonic()
    timed_out = False
    try:
        p = sh(cmd, timeout=CELL_TIMEOUT)
        rc, err = p.returncode, p.stderr.strip()[:400]
    except subprocess.TimeoutExpired:
        rc, err, timed_out = -1, f"timed out after {CELL_TIMEOUT}s", True
    remote(host, "sync")
    elapsed = time.monotonic() - t0

    n = -1
    if not timed_out:
        r = remote(host, f"find {dst} -type f | wc -l")
        try:
            n = int(r.stdout.strip())
        except ValueError:
            pass

    ok = (rc == 0 and n == expect)
    row = {
        "host": hname, "corpus": cname, "arm": arm, "rep": rep,
        "seconds": round(elapsed, 2), "rc": rc, "files": n, "expect": expect,
        "gib": gib, "mib_s": round(gib * 1024 / elapsed, 1) if elapsed else 0,
        "ok": ok, "error": "" if ok else err,
    }
    record(row)
    remote(host, f"rm -rf {dst}")
    remote(host, "sync")
    return row


def write_doc(done):
    lines = [
        "# BENCHMARKSv4 — corpora x hosts, rsync -az vs xsync --streams 4",
        "",
        "Generated by `benches/matrix4.py`. Regenerated after every cell, so a",
        "partial matrix is still readable.",
        "",
        "## Method",
        "",
        "- Source: Mac (M1 Max, 64 GB). Its only NIC is a USB gigabit adapter.",
        "- Arms run back to back per (host, corpus) so they share link conditions.",
        "- Fresh destination per run; teardown outside the timed window.",
        "- Remote `sync` **inside** the timed window, so neither tool is scored on",
        "  data still in the receiver's page cache.",
        "- Exit status and landed file count verified per run; failed cells are",
        "  shown as `FAIL` and excluded from the ratio.",
        f"- {REPS} repetitions; the table reports the **best** run of each cell.",
        "",
        "**Throughput below is logical (corpus bytes / wall clock), not wire",
        "rate.** Both arms compress, so a compressible corpus can and does exceed",
        "the ~112 MiB/s gigabit line rate: `cb7` reports 200-300 MiB/s because it",
        "compresses roughly 2-3x on the wire. Compare arms within a row; do not",
        "read these as link speeds.",
        "",
        "## Corpora",
        "",
        "| corpus | files | logical size | character |",
        "|---|---:|---:|---|",
        "| manga | 56 | 3.75 GiB | a few very large archives, already compressed |",
        "| congress | 1,318,771 | 10.23 GiB | many tiny, highly compressible JSON/XML |",
        "| cb7 | 204,577 | 58.25 GiB | build artifacts, **highly compressible** |",
        "",
        "`cb7` is not comic archives despite the name -- it is a native build",
        "output tree: 26.1 GiB of `.o`, 8.2 GiB `.rlib`, 5.7 GiB `.bin`, 4.9 GiB",
        "`.a`, 4.4 GiB `.rmeta`. Object files compress 2-3x trivially.",
        "",
        "## Hosts",
        "",
        "| host | link | notes |",
        "|---|---|---|",
        "| mars | switched gigabit | Ryzen 9 7900X, 24 threads, NVMe |",
        "| freya | ~800 Mbit mesh (router2) | 32 threads, ZFS |",
        "| orion | switched gigabit | Raspberry Pi 5, 4 cores, NVMe |",
        "",
        "## Results",
        "",
    ]
    for cname, _, expect, gib in CORPORA:
        lines += [f"### {cname} ({expect:,} files, {gib} GiB)", "",
                  "| host | rsync -az | xs --streams 4 | ratio |",
                  "|---|---:|---:|---:|"]
        for hname, _, _ in HOSTS:
            cells = {}
            for arm in ARMS:
                runs = [done[k] for k in done
                        if k[0] == hname and k[1] == cname and k[2] == arm and done[k]["ok"]]
                cells[arm] = min((r["seconds"] for r in runs), default=None)
            def fmt(arm):
                v = cells[arm]
                if v is None:
                    attempted = any(k[0] == hname and k[1] == cname and k[2] == arm for k in done)
                    return "FAIL" if attempted else "—"
                return f"{v:.1f} s ({gib*1024/v:.0f} MiB/s)"
            r, x = cells[ARMS[0]], cells[ARMS[1]]
            ratio = f"**{r/x:.2f}x**" if (r and x) else "—"
            lines.append(f"| {hname} | {fmt(ARMS[0])} | {fmt(ARMS[1])} | {ratio} |")
        lines.append("")
    lines += ["Ratio > 1.00 means xsync is faster.", "",
        "## Reading these numbers",
        "",
        "xsync is faster in 8 of 9 cells. The ninth, manga to mars, is a dead",
        "heat (36.2 s against 36.4 s): 56 large incompressible files over gigabit",
        "is pure bandwidth, both tools sit at line rate, and there is nothing",
        "there to win.",
        "",
        "The pattern is that xsync's lead grows with **per-file overhead** and",
        "with **receiver weakness**, not with raw bandwidth:",
        "",
        "- `congress` is ~1.9-2.2x everywhere. 1.3 million tiny files is a",
        "  per-file-cost workload, and four streams overlap the stalls that a",
        "  single rsync stream serialises.",
        "- `cb7` on mars and freya is only 1.16-1.24x. Bulk volume on a capable",
        "  receiver is the case where rsync is most competitive.",
        "",
        "### The orion cb7 result is mostly about `-z`, not about xsync",
        "",
        "The 7.82x headline (1676.2 s against 214.5 s) is the largest number in",
        "this matrix and the most easily over-read. A control run isolates it:",
        "",
        "| manga to | `rsync -a` | `rsync -az` | cost of `-z` |",
        "|---|---:|---:|---:|",
        "| mars | 36.4 s | 37.9 s | +4% |",
        "| orion | 36.8 s | 107.0 s | **+191%** |",
        "",
        "**Without `-z`, rsync to orion is exactly as fast as to mars** (36.8",
        "against 36.4). So `-z` is nearly free on mars and catastrophic on the",
        "Pi, and that single flag accounts for most of orion's deficit in every",
        "row above.",
        "",
        "These were ruled out as the cause -- all are equivalent between mars and",
        "orion: link (both switched gigabit, single-connection SSH measured at",
        "100 and 108 MiB/s), RTT (0.95 ms against 1.17 ms), negotiated SSH cipher",
        "(aes128-gcm both), rsync version (3.4.4 both ends), and destination disk.",
        "",
        "The mechanism is **not** established. The obvious explanation --",
        "receiver-side decompression saturating a Pi core -- is not supported by",
        "measurement: during `rsync -az` to orion nothing is CPU-saturated (rsync",
        "~5% of one core, sshd ~25%, over 90% of the box idle). Compression",
        "happens on the sender, which is the same Mac for every host, so a",
        "sender-side explanation cannot produce a per-host difference either.",
        "Something about how `-z` interacts with this receiver remains unexplained",
        "and is worth its own investigation.",
        "",
        "The honest summary of that cell: **`rsync -az` is 7.82x slower than",
        "`xs --streams 4` to a Raspberry Pi**, which is true and reproducible",
        "(1676.2 and 1681.3 s across two reps), but it is a fact about `-z` on",
        "that host at least as much as a fact about the two tools.",
        "",
        "## Verification",
        "",
        "Beyond exit status and file count, both arms were checked byte-for-byte",
        "on manga to mars: 4,025,816,305 bytes and SHA-256",
        "`7b303fcc04b267003001926f9f91ceaa33200b3b43e5576cf1d702922d2d3432`,",
        "identical to the source for both tools. File count alone would not catch",
        "truncation, so this was checked separately.",
        "",
              "## Raw", "", "Every run, including repetitions and failures, is in",
              "`benches/results/v4/results.jsonl`.", ""]
    DOC.write_text("\n".join(lines))


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    DOC.parent.mkdir(parents=True, exist_ok=True)
    done = load_done()
    total = REPS * len(HOSTS) * len(CORPORA) * len(ARMS)
    print(f"matrix: {total} cells, {len(done)} already done", flush=True)
    write_doc(done)
    for rep in range(1, REPS + 1):
        for hname, host, _ in HOSTS:
            for cname, src, expect, gib in CORPORA:
                for arm in ARMS:
                    key = (hname, cname, arm, rep)
                    if key in done:
                        print(f"skip  rep{rep} {hname:<6} {cname:<9} {arm}", flush=True)
                        continue
                    print(f"run   rep{rep} {hname:<6} {cname:<9} {arm:<15} ...",
                          end=" ", flush=True)
                    row = run_cell(hname, host, cname, src, expect, gib, arm, rep)
                    status = "OK" if row["ok"] else f"FAIL rc={row['rc']} files={row['files']}"
                    print(f"{row['seconds']:8.1f}s {row['mib_s']:6.1f} MiB/s  {status}",
                          flush=True)
                    if not row["ok"] and row["error"]:
                        print(f"      {row['error'][:200]}", flush=True)
                    done[key] = row
                    write_doc(done)
    write_doc(done)
    print("\nmatrix complete", flush=True)


if __name__ == "__main__":
    main()
